name: http_mocks
version: 0.1.0
description: Mocks for dart:io HTTP requests
homepage: https://github.com/pulyaevskiy/dart-http-mocks
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:
  test: "^0.12.6+1"
  mockito: "^0.11.0"

dev_dependencies:
  dart_coveralls: "^0.4.0"
